import type { Metadata } from "next";
import "./globals.css";
import { Container } from "@/components/Container";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: {
    default: "The blog - This is a Next.js blog.",
    template: "%s | The Blog",
  },
  description: "Generated by BPC",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html>
      <body>
        <Container>
          <Header />

          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
