import type { Metadata } from "next";
import "./globals.css";
import { Container } from "@/components/Container";
import { Header } from "@/components/Header";

export const metadata: Metadata = {
  title: {
    default: "The blog - This is a Next.js blog.",
    template: "%s | The Blog",
  },
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html>
      <body>
        <Container>
          <Header />
        
        {children}
        <footer>
          <p className="text-6xl font-bold text-center py-8">FOOTER</p>
        </footer>
        </Container>
      </body>
    </html>
  );
}
